import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Philodendron Heartleaf",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/Bloomscape-Philodendron-Heartleaf.webp",
    price: "300",
    rating: 4.8,
    categoryName: "Indoor Plants",
  },
  {
    _id: uuid(),
    title: "Cast Iron Plant",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/cast-iron-plant.webp",
    price: "320",
    rating: 4.1,
    categoryName: "Indoor Plants",
  },
  {
    _id: uuid(),
    title: "Golden Pothos",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/golden-pothos.webp",
    price: "200",
    rating: 4.5,
    categoryName: "Indoor Plants",
  },
  {
    _id: uuid(),
    title: "Monstera Deliciosa",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/lon--george-monstera-deliciosa.webp",
    price: "250",
    rating: 4.3,
    categoryName: "Indoor Plants",
  },
  {
    _id: uuid(),
    title: "Lucky Bamboo",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/lucky-bamboo.webp",
    price: "300",
    rating: 3.6,
    categoryName: "Indoor Plants",
  },
  {
    _id: uuid(),
    title: "Snake Plant",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/snake-plant.webp",
    price: "500",
    rating: 3.8,
    categoryName: "Indoor Plants",
  },
  {
    _id: uuid(),
    title: "ZZ Plant",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/zz-plant.webp",
    price: "400",
    rating: 4.9,
    categoryName: "Indoor Plants",
  },
  {
    _id: uuid(),
    title: "Butterfly Bush",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/butterfly_bush_outdoor.jpg",
    price: "500",
    rating: 3.5,
    categoryName: "Outdoor Plants",
  },
  {
    _id: uuid(),
    title: "Sedum",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/sedum_outdoor.jpg",
    price: "420",
    rating: 4.6,
    categoryName: "Outdoor Plants",
  },
  {
    _id: uuid(),
    title: "Daylily",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/daylily_outdoor.jpg",
    price: "260",
    rating: 2.5,
    categoryName: "Outdoor Plants",
  },
  {
    _id: uuid(),
    title: "Carmint",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/carmint_outdoor.jpg",
    price: "450",
    rating: 2.9,
    categoryName: "Outdoor Plants",
  },
  {
    _id: uuid(),
    title: "Daffodils",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/daffodils_outdoor.jpg",
    price: "600",
    rating: 5.0,
    categoryName: "Outdoor Plants",
  },
  {
    _id: uuid(),
    title: "Weeping Fig",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/weeping_fig_air_purifier.jpg",
    price: "310",
    rating: 4.8,
    categoryName: "Air Purifier Plants",
  },
  {
    _id: uuid(),
    title: "Purple Spiderwort",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/purple_spiderwort_air_purifier.jpg",
    price: "400",
    rating: 4.2,
    categoryName: "Air Purifier Plants",
  },
  {
    _id: uuid(),
    title: "Wax Plant",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/wax_plant_air_purifier.jpg",
    price: "500",
    rating: 2.1,
    categoryName: "Air Purifier Plants",
  },
  {
    _id: uuid(),
    title: "Purple Waffle",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/purple_waffle_plant_air_purifier.jpg",
    price: "400",
    rating: 4.9,
    categoryName: "Air Purifier Plants",
  },
  {
    _id: uuid(),
    title: "Bee Balm",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/bee_balm_mosquito_repellent.jpg",
    price: "450",
    rating: 3.4,
    categoryName: "Mosquito Repellent Plants",
  },
  {
    _id: uuid(),
    title: "Scented Geranium",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/scented_geranium_mosquito_repellent.jpg",
    price: "600",
    rating: 5.0,
    categoryName: "Mosquito Repellent Plants",
  },
  {
    _id: uuid(),
    title: "Eucalyptus",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/eucalyptus_mosquito_repellent.jpg",
    price: "310",
    rating: 4.8,
    categoryName: "Mosquito Repellent Plants",
  },
  {
    _id: uuid(),
    title: "Lantana",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/lantana_mosquito_repellent.jpg",
    price: "400",
    rating: 4.2,
    categoryName: "Mosquito Repellent Plants",
  },
  {
    _id: uuid(),
    title: "Mint",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/mint_mosquito_repellent.jpg",
    price: "500",
    rating: 2.1,
    categoryName: "Mosquito Repellent Plants",
  },
  {
    _id: uuid(),
    title: "American Beautyberry",
    imageLink: "https://raw.githubusercontent.com/srinivas180/planty/main/src/images/products/american_beautyberry_mosquito_repellent.jpg",
    price: "400",
    rating: 4.9,
    categoryName: "Mosquito Repellent Plants",
  },
];
